# Generated by Django 4.2.17 on 2024-12-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_watchlistitem_currency"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="watchlistitem",
            constraint=models.UniqueConstraint(
                fields=("user", "symbol"), name="unique_user_symbol"
            ),
        ),
    ]
